version: '3.8'
services:

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./mariadb-config:/etc/mysql/config.d
    command: >
      bash -c "
      cp /etc/mysql/config.d/* /etc/mysql/conf.d/.
      && chmod 644 /etc/mysql/conf.d/*.cnf
      && /usr/local/bin/docker-entrypoint.sh mariadbd
      "
    env_file:
      - ./mariadb.env
    secrets:
      - mariadb-root-password
      - mariadb-password

secrets:
  mariadb-root-password:
    file: secrets/mariadb-root-password.txt
  mariadb-password:
    file: secrets/mariadb-password.txt