version: '3.8'
services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-vhost/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/myapp.conf
      - ./app:/app

  php-fpm:
    image: bitnami/php-fpm:8.0
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    volumes:
      - ./php-fpm/php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ./php-fpm/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
      - ./php-fpm/www.conf.default:/opt/bitnami/php/etc/php-fpm.d/www.conf.default
      - ./app:/app
    env_file:
      - ./mariadb.env
    secrets:
      - mariadb-password
      - email-public-key
      - email-private-key
      - super-admin-password

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./mariadb-config:/etc/mysql/config.d
    command: >
      bash -c "
      cp /etc/mysql/config.d/* /etc/mysql/conf.d/.
      && chmod 644 /etc/mysql/conf.d/*.cnf
      && /usr/local/bin/docker-entrypoint.sh mariadbd
      "
    env_file:
      - ./mariadb.env
    secrets:
      - mariadb-root-password
      - mariadb-password

secrets:
  mariadb-root-password:
    file: secrets/mariadb-root-password.txt
  mariadb-password:
    file: secrets/mariadb-password.txt
  email-public-key:
    file: secrets/email-public-key.txt
  email-private-key:
    file: secrets/email-private-key.txt
  super-admin-password:
    file: secrets/super-admin-password.txt