version: '3.8'
services:

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./mariadb.env
    secrets:
      - mariadb-root-password
      - mariadb-password

secrets:
  mariadb-root-password:
    external: true
  mariadb-password:
    external: true